### PR TITLE
Update to latest TCK

### PR DESCRIPTION
**Pull request by pvlugter**
Update to the latest TCK from https://github.com/cloudstateio/cloudstate/pull/500

I've already published a new `cloudstate-go-tck` docker image with these changes, and which should work for both the current latest TCK as well as the updated TCK in https://github.com/cloudstateio/cloudstate/pull/500

New TCK uncovered some small bugs:
* Value and event sourced entities were not resetting all parts of the context after command processing, so if there's a forward or side effect then it would keep returning these for subsequent commands as well.
* CRDT entities did not specify the `persistenceId`, which is currently used in the proxy as a prefix for CRDT keys. The proxy could use the `serviceName` directly itself, but it currently uses the `persistenceId` so I've updated here to pass the full service name as the persistence id for CRDT entities. This was uncovered when forwarding to the second entity type but with the same entity key.

The passivation timeout is still to be supported, and those are the only pending tests now. I've added commented out service descriptions for these to the updated protobufs (commented out because the TCK checks that there are the same number of entities and gRPC services on entity discovery).

### CODE REVIEW

**Comment by pvlugter** [comment]
Note: didn't remove shopping cart from the TCK, so that it still works with the currently published latest TCK, and because it looks like it's included in the docs.

**Comment by marcellanz** [comment]
Cool! Thanks @pvlugter for the changes and fixes.

For the passivation timeout I have a branch ready for that I wanted to until the reorganisation and passivation stable.

**Comment by marcellanz** [comment]
Looks good to me

**Comment by marcellanz** [comment]
> CRDT entities did not specify the persistenceId, which is currently used in the proxy as a prefix for CRDT keys. The proxy could use the serviceName directly itself, but it currently uses the persistenceId so I've updated here to pass the full service name as the persistence id for CRDT entities

@pvlugter Is setting the persistenceId temporarily or do we mandate that to be set implicit or by the user function on registration explicit in the future? We might have to document it too.
Beside that do we have to set the presistenceId once CRDTs can be persisted at all?

**Comment by pvlugter** [comment]
> > CRDT entities did not specify the persistenceId, which is currently used in the proxy as a prefix for CRDT keys. The proxy could use the serviceName directly itself, but it currently uses the persistenceId so I've updated here to pass the full service name as the persistence id for CRDT entities
> 
> @pvlugter Is setting the persistenceId temporarily or do we mandate that to be set implicit or by the user function on registration explicit in the future? We might have to document it too.
> Beside that do we have to set the presistenceId once CRDTs can be persisted at all?

I think this should be temporary, and the proxy updated to use the service name automatically for the key prefix. I'm not actually sure why persistence ids are required from the language support for any of the entities — seems that the service name could always be used, including for event sourced entities. And that it would be good to also support and include an entity version or similar.

**Pull request merged**
